### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by zygimantus** [ducksoupdev/angular2-express-docker#1]
I am getting this error when opening a webpage on 3000 port:

Error: No default engine was specified and no extension was provided.
   at new View (/home/app/server/node_modules/express/lib/view.js:62:11)
   at EventEmitter.render (/home/app/server/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/home/app/server/node_modules/express/lib/response.js:960:7)
   at app.use (/home/app/server/app.js:40:7)
   at Layer.handle_error (/home/app/server/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/home/app/server/node_modules/express/lib/router/index.js:310:13)
   at /home/app/server/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/app/server/node_modules/express/lib/router/index.js:330:12)
   at next (/home/app/server/node_modules/express/lib/router/index.js:271:10)
   at app.use (/home/app/server/app.js:29:3)

**Comment by JoaquimCMH** [comment]
Did you try with localhost:3000/api?
